server:
  port: 7003
#Eureka配置
eureka:
  instance:
    hostname: eureka7003.com #Eureaka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册中心注册自己
    fetch-registry: false #如果fetch-registry为false，则表示自己为注册中心
    service-url: #监控页面
      #单机：点进去参考源码，可看到默认的url端口配置为8761，我们设置为自己的端口。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

      #集群（除自身外 关联其他所有）
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
