server:
  port: 9527
#spring的配置
spring:
  application:
    name : springcloud-zuul
#EUREKA的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost.com:7002/eureka/,http://localhost.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
    #隐藏真实ip
zuul:
  routes:
    # 设置服务a 路径名称 随便起
    service-a:
      path: /service-a/**
      # 这里写a服务的注册名字
      serviceId: springcloud-provider-dept
    # 设置服务b 路径名称 随便起
    service-b:
      path: /service-b/**
      # 这里写b服务的注册名字
      serviceId: springcloud-provider-dept

